chore: cleanup for PR

diff --git a/.github/workflows/build-ampd-release.yaml b/.github/workflows/build-ampd-release.yaml
--- a/.github/workflows/build-ampd-release.yaml
+++ b/.github/workflows/build-ampd-release.yaml
@@ -1,9 +1,6 @@
 name: ampd - Build and release binary and image
 
 on:
-  push:
-    branches:
-      - feat/put-ampd-releases-on-r2
   workflow_dispatch:
     inputs:
       tag:
@@ -23,18 +20,17 @@ jobs:
         id: extract_semver
         run: |
           full_semver=$(echo ${{ github.event.inputs.tag }} | sed 's/ampd-//')
-          full_semver="v1.1.1"
           version_number=$(echo $full_semver | sed 's/^v//')
           echo "semver=$full_semver" >> $GITHUB_OUTPUT
           echo "version=$version_number" >> $GITHUB_OUTPUT
 
-#      - name: Validate tag
-#        env:
-#          TAG: ${{ github.event.inputs.tag }}
-#          SEMVER: ${{ steps.extract_semver.outputs.semver }}
-#        run: |
-#          if [[ $TAG =~ ampd-v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]]; then echo "Tag is okay" && exit 0; else echo "invalid tag" && exit 1; fi
-#          aws s3 ls s3://axelar-releases/ampd/"$SEMVER" && echo "tag already exists, use a new one" && exit 1
+      - name: Validate tag
+        env:
+          TAG: ${{ github.event.inputs.tag }}
+          SEMVER: ${{ steps.extract_semver.outputs.semver }}
+        run: |
+          if [[ $TAG =~ ampd-v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]]; then echo "Tag is okay" && exit 0; else echo "invalid tag" && exit 1; fi
+          aws s3 ls s3://axelar-releases/ampd/"$SEMVER" && echo "tag already exists, use a new one" && exit 1
 
 
 
@@ -43,7 +39,7 @@ jobs:
     needs: extract-semver
     strategy:
       matrix:
-        os: [ ubuntu-22.04 ]
+        os: [ ubuntu-22.04, macos-12 ]
         arch: [ amd64, arm64 ]
 
     permissions:
@@ -169,22 +165,22 @@ jobs:
             shasum -a 256 $i.zip | awk '{print $1}' > $i.zip.sha256
           done
 
-#      - name: Upload binaries to release
-#        uses: svenstaro/upload-release-action@v2
-#        with:
-#          repo_token: ${{ secrets.GITHUB_TOKEN }}
-#          file: ./ampdbin/*
-#          tag: ${{ github.event.inputs.tag }}
-#          overwrite: true
-#          file_glob: true
+      - name: Upload binaries to release
+        uses: svenstaro/upload-release-action@v2
+        with:
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
+          file: ./ampdbin/*
+          tag: ${{ github.event.inputs.tag }}
+          overwrite: true
+          file_glob: true
 
-#      - name: Upload binaries to S3
-#        env:
-#          S3_PATH: s3://axelar-releases/ampd/${{ needs.extract-semver.outputs.semver }}
-#        run: |
-#          aws s3 cp ./ampdbin ${S3_PATH}/ --recursive
+      - name: Upload binaries to S3
+        env:
+          S3_PATH: s3://axelar-releases/ampd/${{ needs.extract-semver.outputs.semver }}
+        run: |
+          aws s3 cp ./ampdbin ${S3_PATH}/ --recursive
 
-      - name: Prepare directory source directory structure for r2 upload
+      - name: Prepare source directory structure for r2 upload
         id: prepare-r2-release
         run: |
           version="${{ needs.extract-semver.outputs.version }}"
@@ -203,69 +199,69 @@ jobs:
           source-dir: ${{ steps.prepare-r2-release.outputs.release-dir }}
           destination-dir: ${{ steps.prepare-r2-release.outputs.r2-destination-dir }}
 
-#  release-docker:
-#    runs-on: ubuntu-22.04
-#    needs: extract-semver
-#    permissions:
-#      contents: write
-#      packages: write
-#      id-token: write
-#    steps:
-#      - name: Checkout code
-#        uses: actions/checkout@v4
-#        with:
-#          fetch-depth: '0'
-#          ref: ${{ github.event.inputs.tag }}
-#          submodules: recursive
-#
-#      - name: Set up QEMU
-#        uses: docker/setup-qemu-action@v3
-#
-#      - name: Set up Docker Buildx
-#        id: buildx
-#        uses: docker/setup-buildx-action@v3
-#
-#      - name: Login to DockerHub
-#        uses: docker/login-action@v3
-#        with:
-#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-#          password: ${{ secrets.DOCKER_HUB_TOKEN }}
-#
-#      - name: Build and push docker images
-#        env:
-#          PLATFORM: linux/amd64
-#          SEMVER: ${{ needs.extract-semver.outputs.semver }}
-#        run: |
-#          make build-push-docker-images
+  release-docker:
+    runs-on: ubuntu-22.04
+    needs: extract-semver
+    permissions:
+      contents: write
+      packages: write
+      id-token: write
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: '0'
+          ref: ${{ github.event.inputs.tag }}
+          submodules: recursive
 
-#  combine-sign:
-#    needs: [ release-docker, extract-semver ]
-#    runs-on: ubuntu-22.04
-#    permissions:
-#      contents: write
-#      packages: write
-#      id-token: write
-#    steps:
-#      - name: Install Cosign
-#        uses: sigstore/cosign-installer@v3.3.0
-#        with:
-#          cosign-release: 'v2.2.2'
-#
-#      - name: Login to DockerHub
-#        uses: docker/login-action@v3
-#        with:
-#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-#          password: ${{ secrets.DOCKER_HUB_TOKEN }}
-#
-#      - name: Create multiarch manifest
-#        env:
-#          SEMVER: ${{ needs.extract-semver.outputs.semver }}
-#        run: |
-#          docker buildx imagetools create -t axelarnet/axelar-ampd:${SEMVER} \
-#            axelarnet/axelar-ampd-linux-amd64:${SEMVER}
-#
-#      - name: Sign the images with GitHub OIDC
-#        run: cosign sign -y --oidc-issuer https://token.actions.githubusercontent.com ${TAGS}
-#        env:
-#          TAGS: axelarnet/axelar-ampd:${{ needs.extract-semver.outputs.semver }}
-#          COSIGN_EXPERIMENTAL: 1
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
+      - name: Set up Docker Buildx
+        id: buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Login to DockerHub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_TOKEN }}
+
+      - name: Build and push docker images
+        env:
+          PLATFORM: linux/amd64
+          SEMVER: ${{ needs.extract-semver.outputs.semver }}
+        run: |
+          make build-push-docker-images
+
+  combine-sign:
+    needs: [ release-docker, extract-semver ]
+    runs-on: ubuntu-22.04
+    permissions:
+      contents: write
+      packages: write
+      id-token: write
+    steps:
+      - name: Install Cosign
+        uses: sigstore/cosign-installer@v3.3.0
+        with:
+          cosign-release: 'v2.2.2'
+
+      - name: Login to DockerHub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_TOKEN }}
+
+      - name: Create multiarch manifest
+        env:
+          SEMVER: ${{ needs.extract-semver.outputs.semver }}
+        run: |
+          docker buildx imagetools create -t axelarnet/axelar-ampd:${SEMVER} \
+            axelarnet/axelar-ampd-linux-amd64:${SEMVER}
+
+      - name: Sign the images with GitHub OIDC
+        run: cosign sign -y --oidc-issuer https://token.actions.githubusercontent.com ${TAGS}
+        env:
+          TAGS: axelarnet/axelar-ampd:${{ needs.extract-semver.outputs.semver }}
+          COSIGN_EXPERIMENTAL: 1
